'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings), MySettings)

#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
        Private Shared addedHandler As Boolean

        Private Shared addedHandlerLockObject As New Object

        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
            If My.Application.SaveMySettingsOnExit Then
                My.Settings.Save()
            End If
        End Sub
#End If
#End Region

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("\\padaniafile.padania.local\piazza\Guardamiglio\11 - UFFICIO FORNITORI\FORNITORI\LISTINI E PROMO FORNITORI")> _
        Public Property UltimaCartellaPDF() As String
            Get
                Return CType(Me("UltimaCartellaPDF"), String)
            End Get
            Set
                Me("UltimaCartellaPDF") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\appoggio\MD FATTURE\ZIP")> _
        Public Property CartellaZip() As String
            Get
                Return CType(Me("CartellaZip"), String)
            End Get
            Set
                Me("CartellaZip") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\appoggio\MD FATTURE\P7M")> _
        Public Property CartellaDecompressi() As String
            Get
                Return CType(Me("CartellaDecompressi"), String)
            End Get
            Set
                Me("CartellaDecompressi") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\appoggio\MD FATTURE\XML")> _
        Public Property CartellaXmlPronti() As String
            Get
                Return CType(Me("CartellaXmlPronti"), String)
            End Get
            Set
                Me("CartellaXmlPronti") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\appoggio\MD FATTURE\BACKUPXML")> _
        Public Property CartellaBackup() As String
            Get
                Return CType(Me("CartellaBackup"), String)
            End Get
            Set
                Me("CartellaBackup") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\appoggio\MD FATTURE\XMLDOPPI")> _
        Public Property CartellaDoppi() As String
            Get
                Return CType(Me("CartellaDoppi"), String)
            End Get
            Set
                Me("CartellaDoppi") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0.02")> _
        Public Property ScostamentoAccettabile() As Decimal
            Get
                Return CType(Me("ScostamentoAccettabile"), Decimal)
            End Get
            Set
                Me("ScostamentoAccettabile") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("90")> _
        Public Property GiorniImportazioneListini() As Integer
            Get
                Return CType(Me("GiorniImportazioneListini"), Integer)
            End Get
            Set
                Me("GiorniImportazioneListini") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("90")> _
        Public Property GiorniImportazioneFattureAS400() As Integer
            Get
                Return CType(Me("GiorniImportazioneFattureAS400"), Integer)
            End Get
            Set
                Me("GiorniImportazioneFattureAS400") = value
            End Set
        End Property

        Public Shared ReadOnly Property [Default]() As MySettings
            Get

#If _MyType = "WindowsForms" Then
                   If Not addedHandler Then
                        SyncLock addedHandlerLockObject
                            If Not addedHandler Then
                                AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                                addedHandler = True
                            End If
                        End SyncLock
                    End If
#End If
                Return defaultInstance
            End Get
        End Property
    End Class
End Namespace

Namespace My

    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
    Friend Module MySettingsProperty

        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")> _
        Friend ReadOnly Property Settings() As Global.Gestione_Fatture_e_Listini.My.MySettings
            Get
                Return Global.Gestione_Fatture_e_Listini.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
